### ISSUE TITLE
update and packaging zope index

### ISSUE THREAD

**Issue by mamico** [Toblerity/zope.index.rtree#2]
@hobu I need a ZCatalog index for geospatial point on Plone/Zope, so I started to experiment using RTree and most of the code here for create a new package, that works as an addon, with recent Zope/Plone

https://github.com/mamico/collective.geoindex

It is still in the early stages (even the name may not be the final one). At the end of the work I am thinking of proposing to move the repository to zopefundation or plone/collective umbrella

I wrote here to see if it's okay for you and if you have any pointers/suggestions, such as which license to apply or the package name.

Thanks in advance.

**Comment by hobu** [comment]
sorry, I haven't worked with zope in 15 years. I've no issues with moving this stuff to where it make sense given the community that might be using it. 

I have no opinion on what licensing to choose and if you have seen some of the names of my software projects, you do not want my opinion on project names.

**Comment by mamico** [comment]
thanks
